name: myshop
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.18.1
  provider: ^6.0.3
  flutter_dotenv: ^5.0.2
  http: ^0.13.4
  shared_preferences: ^2.0.15
  carousel_slider: ^4.2.1
  fan_carousel_image_slider: ^0.1.2
  google_fonts: ^4.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3


flutter:
  uses-material-design: true
  assets:
  - assets/image/
  - .env
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf

        